--- # Create ec2 instance playbook

- name: Create an instance
  connection: local
  hosts: localhost
  gather_facts: false
  vars:
    image: "ami-02e44367276fe7adc"
    instance_type: "r5.large"
    security_group_name: "nomachine"
    vm: "remote"

  tasks:

    - name: Create security group
      ec2_group:
        name: "{{ security_group_name }}"
        description: Nomachine connection
        region: "{{ region }}"
        state: present
        vpc_id: "{{ vpc_id }}"
        purge_rules: true
        rules:
          - proto: tcp
            ports:
              - 4000
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 4000
          - proto: udp
            ports:
              - 4001
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 4001
      register: secgroup_info

    - name: Create instance
      ec2:
        image: "{{ image }}"
        instance_type: "{{ instance_type }}"
        keypair: "{{ keypair }}"
        instance_tags:
          Name: "{{ vm }}"
        region: "{{ region }}"
        group: "{{ security_group_name }}"
        wait: true
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ ec2.instances[0].public_ip }} groups=aws_instances

    - name: Wait for SSH to come up
      wait_for: host={{ ec2.instances[0].public_ip }} port=22 delay=60 timeout=640 state=started


- name: Manage new instances
  hosts: aws_instances
  connection: ssh
  become: True
  roles:
    - remote