--- # Google Cloud Platform instance playbook

- name: Create an instance
  hosts: localhost
  gather_facts: false
  vars:
    address: "remote-address"
    disk: "remote-root"
    gcp_cred_kind: "serviceaccount"
    firewall: "nomachine-allow"
    vm: "remote"
    vm_size: 16
    vm_type: "e2-standard-4"

  tasks:
    - name: Create a firewall rule for nomachine
      google.cloud.gcp_compute_firewall:
        name: "{{ firewall }}"
        allowed:
          - ip_protocol: tcp
            ports:
              - '4000'
          - ip_protocol: udp
            ports:
              - '4001'
        target_tags:
          - "{{ firewall }}"
        project: "{{ project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ sa_key }}"
        state: present

    - name: Create the root disk
      gcp_compute_disk:
        name: '{{ disk }}'
        size_gb: "{{ vm_size }}"
        source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts'
        zone: "{{ region }}-{{ zone }}"
        project: "{{ project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ sa_key }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: disk1

    - name: Create a address
      gcp_compute_address:
        name: "{{ address }}"
        region: "{{ region }}"
        project: "{{ project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ sa_key }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: address

    - name: Create a instance
      gcp_compute_instance:
        state: present
        name: "{{ vm }}"
        machine_type: "{{ vm_type }}"
        disks:
          - auto_delete: true
            boot: true
            source: "{{ disk1 }}"
        network_interfaces:
          - network: null
            access_configs:
              - name: 'External NAT'
                nat_ip: "{{ address }}"
                type: 'ONE_TO_ONE_NAT'
        zone: "{{ region }}-{{ zone }}"
        tags:
          items:
            - "{{ firewall }}"
        project: "{{ project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ sa_key }}"
        scopes:
          - https://www.googleapis.com/auth/compute
      register: instance

    - name: Wait for SSH to come up
      wait_for: host={{ address.address }} port=22 delay=30 timeout=640

    - name: Add host to groupname
      add_host: hostname={{ address.address }} groupname=gcp_instances

- name: Manage new instances
  hosts: gcp_instances
  connection: ssh
  become: True
  roles:
    - remote
