--- # Linode instance playbook

- name: Create an instance
  hosts: localhost
  gather_facts: false
  vars:
    vm: "remote"
    image: "linode/ubuntu20.04"
    vm_plan: "g6-standard-6"
    ssh_wait: 1200

  tasks:

    - name: Create a new server
      community.general.linode_v4:
        label: "{{ vm }}"
        type: "{{ vm_plan }}"
        region: "{{ region }}"
        image: "{{ image }}"
        root_pass: "{{ root_pass }}"
        authorized_keys:
          - "{{ lookup('file', '{{ pub_key }}') }}"
        state: present
      delegate_to: localhost
      register: instance

    - name: Wait for SSH to come up
      wait_for: host={{ instance.instance.ipv4[0] }} port=22 delay=30 timeout={{ ssh_wait }}

    - name: Add host to groupname
      add_host: hostname={{ instance.instance.ipv4[0] }} groupname=linode_instances

- name: Manage new instances
  hosts: linode_instances
  connection: ssh
  become: True
  roles:
    - remote
