--- # roles/remote/tasks/packages.yml

- name: Install apt packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - dconf-editor
      - docker-compose
      - docker.io
      - ffmpeg
      - filezilla
      - gcc
      - git
      - git-flow
      - gnome-tweaks
      - gnupg
      - locate
      - lsb-release
      - make
      - meld
      - nethogs
      - net-tools
      - python3-pip
      - terminator
      - vim
      - wget
  tags: package-basic
- name: Remove few apt unused packages
  apt:
    pkg:
      - libreoffice-*
      - thunderbird
    state: absent
- name: Install snap packages
  community.general.snap:
    name:
      - code
      - dbeaver-ce
      - helm
      - kubectl
      - pycharm-community
      - p7zip-desktop
    classic: true
- name: Install azure-cli
  shell: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  args:
    executable: /bin/bash
  tags: package-cloud
- name: Install aws-cli
  community.general.snap:
    name:
      - aws-cli
    classic: true
  tags: package-cloud
- name: Install gcloud
  shell: |
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" \
      | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
      && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg \
      | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && \
      apt-get update -y && apt-get install google-cloud-sdk -y
  args:
    executable: /bin/bash
  tags: package-cloud
- name: Remove useless packages from the cache
  apt:
    autoclean: true
- name: Remove dependencies that are no longer required
  apt:
    autoremove: true